stages:
  - Build

Build:
  stage: Build
  script:
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - terraform plan -out=tfplan
    - terraform apply tfplan
    - terraform output > outputs.txt
  artifacts:
    paths:
      - ./tfplan
      - ./outputs.txt